#!/usr/bin/env python3
"""Generate a torch-free, CUDA-parity copy of the packaged CPU oversampler.

Reads ``src/gaussifier_sampler/native_sampler_backend/cpu/csrc/density_points.cpp``
and writes ``build/dp_wasm.cpp`` with four deliberate changes:

1. LibTorch removed (raw pointers in, raw pointer out).
2. ``unit_interval_from_seed`` uses the CUDA hash convention: the state is
   hashed directly, without the splitmix64 increment the CPU file applies.
   The packaged CPU file and the CUDA kernel disagree on this one function,
   and the production path is the CUDA kernel.
3. A ``tile_cap`` argument mirrors the CUDA shared-memory cap
   (``tile_size = min(tile_size, 32)``); pass 0 to disable it.
4. An ``extern "C"`` entry point for Emscripten.

Every anchor must match exactly once; the script fails loudly otherwise.
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PACKAGE = HERE.parent
DEFAULT_SOURCE = (
    PACKAGE.parents[2]
    / "src"
    / "gaussifier_sampler"
    / "native_sampler_backend"
    / "cpu"
    / "csrc"
    / "density_points.cpp"
)
DEFAULT_OUTPUT = PACKAGE / "build" / "dp_wasm.cpp"

CUDA_UNIT_INTERVAL = """double unit_interval_from_seed(int64_t seed, int64_t salt) {
  // CUDA convention (error_diffusion_kernel.cu): hash the state directly, no
  // splitmix64 increment. The packaged CPU file adds the increment and
  // therefore samples a different point set; production uses the CUDA path.
  uint64_t value = static_cast<uint64_t>(seed) +
      0x9E3779B97F4A7C15ULL * (static_cast<uint64_t>(salt) + 1ULL);
  value = (value ^ (value >> 30)) * 0xBF58476D1CE4E5B9ULL;
  value = (value ^ (value >> 27)) * 0x94D049BB133111EBULL;
  value ^= (value >> 31);
  return static_cast<double>(value >> 11) * (1.0 / static_cast<double>(1ULL << 53));
}"""

REPLACEMENTS: list[tuple[str, str]] = [
    (
        "#include <torch/extension.h>\n",
        "// Generated by web/packages/wasm-oversampler/tools/transform.py. Do not edit.\n",
    ),
    (
        """double unit_interval_from_seed(int64_t seed, int64_t salt) {
  uint64_t state = static_cast<uint64_t>(seed) +
      0x9E3779B97F4A7C15ULL * (static_cast<uint64_t>(salt) + 1ULL);
  const uint64_t value = splitmix64_next(state);
  return static_cast<double>(value >> 11) * (1.0 / static_cast<double>(1ULL << 53));
}""",
        CUDA_UNIT_INTERVAL,
    ),
    (
        """torch::Tensor generate_density_points(
    torch::Tensor density,
    int64_t count,
    int64_t height,
    int64_t width,
    int64_t seed) {""",
        """int64_t generate_density_points(
    const float* density_ptr,
    int64_t count,
    int64_t height,
    int64_t width,
    int64_t seed,
    int64_t tile_cap,
    float* points_ptr) {""",
    ),
    (
        """  auto points = torch::empty({count, 2}, torch::dtype(torch::kFloat32).device(torch::kCPU));
  if (count <= 0 || size <= 0) {
    return points;
  }""",
        """  if (count <= 0 || size <= 0) {
    return 0;
  }""",
    ),
    (
        """  const int64_t tile_size = std::clamp<int64_t>(
      static_cast<int64_t>(std::llround(mean_spacing * 4.0)),
      4,
      std::max<int64_t>(4, std::min<int64_t>(height, width)));""",
        """  const int64_t tile_size_uncapped = std::clamp<int64_t>(
      static_cast<int64_t>(std::llround(mean_spacing * 4.0)),
      4,
      std::max<int64_t>(4, std::min<int64_t>(height, width)));
  // CUDA caps the tile at 32 (shared-memory budget) and re-applies the floor of 4.
  const int64_t tile_size = tile_cap > 0
      ? std::max<int64_t>(4, std::min<int64_t>(tile_size_uncapped, tile_cap))
      : tile_size_uncapped;""",
    ),
    (
        """  AT_DISPATCH_FLOATING_TYPES(density.scalar_type(), "density_points_tile_scan", [&] {
    const scalar_t* density_ptr = density.data_ptr<scalar_t>();
""",
        "  {\n",
    ),
    (
        "    }\n  });\n",
        "    }\n  }\n",
    ),
    (
        "  float* points_ptr = points.data_ptr<float>();\n",
        "",
    ),
    (
        """  TORCH_CHECK(cursor == count, "internal error: emitted point count does not match target count");
  return points;""",
        """  if (cursor != count) {
    return -1;
  }
  return cursor;""",
    ),
]

TAIL_ANCHOR = "torch::Tensor density_to_points("

EXTERN_C = '''
extern "C" int64_t gs_density_to_points(
    const float* density,
    int64_t height,
    int64_t width,
    int64_t count,
    int64_t seed,
    int64_t tile_cap,
    float* out) {
  if (density == nullptr || out == nullptr) {
    return -2;
  }
  if (count <= 0 || height <= 0 || width <= 0) {
    return 0;
  }
  return generate_density_points(density, count, height, width, seed, tile_cap, out);
}
'''


def transform(source: str) -> str:
    text = source
    for anchor, replacement in REPLACEMENTS:
        occurrences = text.count(anchor)
        if occurrences != 1:
            raise SystemExit(
                f"transform.py: anchor matched {occurrences} times, expected 1:\n{anchor}"
            )
        text = text.replace(anchor, replacement)
    if text.count(TAIL_ANCHOR) != 1:
        raise SystemExit(f"transform.py: tail anchor missing: {TAIL_ANCHOR}")
    text = text[: text.index(TAIL_ANCHOR)] + EXTERN_C
    leftovers = [line for line in text.splitlines() if "torch" in line.lower() or "AT_DISPATCH" in line]
    if leftovers:
        raise SystemExit("transform.py: torch references survived:\n" + "\n".join(leftovers))
    return text


def main(argv: list[str]) -> int:
    source = Path(argv[1]) if len(argv) > 1 else DEFAULT_SOURCE
    output = Path(argv[2]) if len(argv) > 2 else DEFAULT_OUTPUT
    text = transform(source.read_text(encoding="utf-8"))
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")
    print(f"wrote {output} ({text.count(chr(10))} lines) from {source}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
